### ISSUE TITLE
Growing memory usage.

### ISSUE THREAD

**Issue by ghost** [erijo/transparent-proxy#1]
Hello **erijo**!

I've tried this code but there is a memory leak.
Debug output after one request:

> (Pdb) from guppy import hpy
> (Pdb) hh = hpy()
> (Pdb) before = hh.heap()
> (Pdb) after = hh.heap()
> (Pdb) delta = after - before
> (Pdb) print delta
> Partition of a set of 5079 objects. Total size = 521828 bytes.
>  Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
>      0    409   8   160940  31    160940  31 dict (no owner)
>      1   2366  47   102748  20    263688  51 str
>      2     40   1    67040  13    330728  63 dict of __main__.ProxyRequest
>      3    928  18    59264  11    389992  75 list
>      4     40   1    23128   4    413120  79 unicode
>      5     40   1    20960   4    434080  83 dict of __main__.ProxyClientFactory
>      6     40   1    20960   4    455040  87 dict of twisted.internet.tcp.Server
>      7     80   2    11200   2    466240  89 dict of twisted.internet.address.IPv4Address
>      8     80   2    11200   2    477440  91 dict of twisted.logger._logger.Logger
>      9     80   2    11200   2    488640  94 dict of twisted.web.http_headers.Headers

Every request raises count of all this objects and allocates more and more memory.
One more request after:

> (Pdb) after = hh.heap()
> (Pdb) delta = after - before
> (Pdb) print delta
> Partition of a set of 10711 objects. Total size = 1104316 bytes.
>  Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
>      0    852   8   337776  31    337776  31 dict (no owner)
>      1   4970  46   217372  20    555148  50 str
>      2     84   1   140784  13    695932  63 dict of __main__.ProxyRequest
>      3   1924  18   122960  11    818892  74 list
>      4     84   1    48528   4    867420  79 unicode
>      5     84   1    44016   4    911436  83 dict of __main__.ProxyClientFactory
>      6     84   1    44016   4    955452  87 dict of twisted.internet.tcp.Server
>      7    168   2    23520   2    978972  89 dict of twisted.internet.address.IPv4Address
>      8    168   2    23520   2   1002492  91 dict of twisted.logger._logger.Logger
>      9    168   2    23520   2   1026012  93 dict of twisted.web.http_headers.Headers
> <24 more rows. Type e.g. '_.more' to view.>

I've tried to fix it by myself but im not so skilled in Twisted.
Hope you know how to fix it ;)
Best regards.

**Comment by erijo** [comment]
Thanks for your report. I haven't had time to look into it yet, but I guess that most likely it's some kind of circular references that don't get freed correctly.
