### ISSUE TITLE
Connection close porpuse

### ISSUE THREAD

**Issue by ddor254** [erijo/transparent-proxy#2]
What is the porpuse of the connection close line in the request that go out to the real server ? 

And when i am removing that line , i get exception when i do self.finish() in the clentProxy request.

Can you please elaborate

**Comment by erijo** [comment]
Since there is no support for keep-alive in the code there is no point in asking the server to keep the connection alive. Thus that header is set if needed.

**Comment by ddor254** [comment]
what will be the keep alive support that i will need to add???

**Comment by erijo** [comment]
If you want keep alive to work I guess you need to keep the socket open between requests. How you would go about to do so is not something that I have thought anything about so I can't help you there.

**Comment by ddor254** [comment]
does this proxy support download of files from internet?

**Comment by erijo** [comment]
I see no reason why it shouldn't work.
